notifications:
  email: false
addons:
  apt:
    packages:
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libssl-dev
    - libncurses5-dev
    - make
    - exuberant-ctags
    - automake
    - autoconf
    - libtool
    - g++
    - ragel
    - cmake
    - re2c
    - libcurl4-gnutls-dev
    - python

os:
  - linux
#   - osx 
# matrix:
#   allow_failures:
#     - os: osx
# TODO manage packages
    
language: c # shell really
before_script:
  - sudo chmod 775 /var/run/screen
  - make -C urbit/
  - git -C arvo/ checkout $(git -C arvo/ name-rev --name-only HEAD | sed sI.*/II) # XX branch name for -s
script:
  >
    bin/fake-urbit zod marzod &&
    [ "~zod" = $(bin/urb ships/zod -d our) ] &&
    [ "~marzod" = $(bin/urb ships/zod -d our) ]
