notifications:
  email: false
addons:
  apt:
    packages:
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libssl-dev
    - libncurses5-dev
    - make
    - exuberant-ctags
    - automake
    - autoconf
    - libtool
    - g++
    - ragel
    - cmake
    - re2c
    - libcurl4-gnutls-dev
    - python

os:
  - linux
#   - osx 
# matrix:
#   allow_failures:
#     - os: osx
# TODO manage packages
    
language: c # shell really
cache:
  directories: .travis-cache
before_script:
  - >
      mkdir urbit/bin;
      CACHED=.travis-cache/$(git -C urbit/ rev-parse HEAD);
      cp -p $CACHED-urbit urbit/bin || {
       make -C urbit/ &&
       cp urbit/bin/urbit $CACHED-urbit
      }
  - git -C arvo/ checkout $(git -C arvo/ name-rev --name-only HEAD | sed sI.*/II) # XX branch name for -s
  - sudo chmod 775 /var/run/screen # XX screen seems to be broken by default
script:
  >
    bin/fake-urbit zod marzod &&
    [ "~zod" = $(bin/urb ships/zod -d our) ] &&
    [ "~marzod" = $(bin/urb ships/zod -d our) ]
